"""Seed ontology for GreenGru industrial metallurgical & regulatory Graph RAG.

Layers (NetworkX first): process → material → customs → CBAM boundary →
emission → BAT (STM BREF surface-treatment KB) → Stage-3 scoring rubric.

BAT markdown lives under knowledge/bat/ (STM BREF Draft 1 extract). Nodes
are citation pointers only — never a regulated-value source. Stage-3 rubric
nodes describe marking rules (PRD §8.5 / threshold_scoring.py); grades and
tariffs are still computed only by deterministic code.

CN customs nodes cover PRD §6.1 steel products, supporting both downstream
fasteners (CN 7318) and fabricated steel structures / EN 1090 beams (CN 7308).

Annex II iron/steel note: CBAM certificates price *direct* emissions.
Electricity (Scope 2) may appear as MONITORING_ONLY_NOT_CBAM_PRICED for
advisory clarity and financing scores — never as a CBAM tariff input.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Nodes — id is stable; name_en / name_zh for bilingual UI
# ---------------------------------------------------------------------------

NODES: list[dict[str, Any]] = [
    # —— BAT (STM BREF — replaces 十五五 policy layer) ——
    {
        "id": "bat_stm_bref_root",
        "layer": "bat",
        "name_en": "STM BREF Draft 1 (Feb 2025) — surface treatment of metals",
        "name_zh": "STM BREF 草案1（2025-02）· 金属表面处理",
        "document": "EC JRC Best Available Techniques Reference Document for the Surface Treatment of Metals and Plastics (STM BREF), Draft 1, February 2025",
        "source_file": "knowledge/bat/README.md",
        "note_en": "Citation KB only — never read into tCO2e / tariff / CISA / subsidy arithmetic.",
        "note_zh": "仅作引用知识库 — 不得写入 tCO2e / 关税 / CISA / 补贴算术。",
    },
    {
        "id": "bat_pretreatment_pickling",
        "layer": "bat",
        "name_en": "BAT · Pretreatment — pickling, descaling, degreasing, rinsing",
        "name_zh": "BAT · 前处理 — 酸洗/除鳞/脱脂/漂洗",
        "document": "STM BREF Draft 1 Ch.2.1.4–2.1.6",
        "source_file": "knowledge/bat/pretreatment_pickling_descaling/pretreatment-pickling-descaling.md",
        "steel_relevance": "Universal first step before steel surface treatment",
    },
    {
        "id": "bat_zinc_chromium_plating",
        "layer": "bat",
        "name_en": "BAT · Zinc / chromium plating & conversion coatings (fasteners)",
        "name_zh": "BAT · 锌/铬电镀与转化膜（紧固件）",
        "document": "STM BREF Draft 1 Ch.2.2.1.3–2.2.1.5",
        "source_file": "knowledge/bat/zinc_chromium_plating_fasteners/zinc-chromium-plating-fasteners.md",
        "steel_relevance": "Core corrosion protection for bolts/fasteners/structural steel (jig/barrel)",
    },
    {
        "id": "bat_continuous_coil_coating",
        "layer": "bat",
        "name_en": "BAT · Continuous steel coil coating (zinc/tin/ECCS)",
        "name_zh": "BAT · 连续钢卷涂层（锌/锡/ECCS）",
        "document": "STM BREF Draft 1 Ch.2.4 / Ch.3.3",
        "source_file": "knowledge/bat/continuous_steel_coil_coating/continuous-steel-coil-coating-processes.md",
        "steel_relevance": "Anchor-enterprise coil line (Baowu/Ansteel) feeding SME fabrication",
    },
    {
        "id": "bat_steel_enamelling",
        "layer": "bat",
        "name_en": "BAT · Porcelain (vitreous) enamelling of steel",
        "name_zh": "BAT · 钢铁搪瓷（搪瓷釉）",
        "document": "STM BREF Draft 1 Ch.2.8.3.3.1",
        "source_file": "knowledge/bat/steel_enamelling/enamelling-of-steel.md",
    },
    {
        "id": "bat_cross_cutting_ems_energy",
        "layer": "bat",
        "name_en": "Cross-cutting BAT · EMS, monitoring, energy efficiency",
        "name_zh": "横断 BAT · 环境管理/监测/能效",
        "document": "STM BREF Draft 1 Ch.4.1–4.2",
        "source_file": "knowledge/bat/cross_cutting_bat/01-general-performance-monitoring-energy.md",
    },
    {
        "id": "bat_cross_cutting_decarb_water",
        "layer": "bat",
        "name_en": "Cross-cutting BAT · Decarbonisation, water, materials efficiency",
        "name_zh": "横断 BAT · 脱碳/水/物料效率",
        "document": "STM BREF Draft 1 Ch.4.2",
        "source_file": "knowledge/bat/cross_cutting_bat/02-decarbonisation-water-materials-efficiency.md",
    },
    {
        "id": "bat_cross_cutting_crvi_substitution",
        "layer": "bat",
        "name_en": "Cross-cutting BAT · Chemicals substitution (Cr(VI) replacement)",
        "name_zh": "横断 BAT · 化学品替代（六价铬 Cr(VI) 替代）",
        "document": "STM BREF Draft 1 Ch.4.2.7",
        "source_file": "knowledge/bat/cross_cutting_bat/03-chemicals-substitution.md",
        "steel_relevance": "Directly relevant to fastener passivation / conversion coatings",
    },
    {
        "id": "bat_cross_cutting_air_noise",
        "layer": "bat",
        "name_en": "Cross-cutting BAT · Emissions to air & noise",
        "name_zh": "横断 BAT · 废气与噪声",
        "document": "STM BREF Draft 1 Ch.4.2",
        "source_file": "knowledge/bat/cross_cutting_bat/04-emissions-to-air-noise.md",
    },
    {
        "id": "bat_cross_cutting_wastewater",
        "layer": "bat",
        "name_en": "Cross-cutting BAT · Waste water, residues, industrial symbiosis",
        "name_zh": "横断 BAT · 废水/残渣/工业共生",
        "document": "STM BREF Draft 1 Ch.4.2",
        "source_file": "knowledge/bat/cross_cutting_bat/05-wastewater-residues-industrial-symbiosis.md",
    },
    {
        "id": "bat_electroplating_specific",
        "layer": "bat",
        "name_en": "BAT · Electroplating / chemical plating (material efficiency, drag-out, air)",
        "name_zh": "BAT · 电镀/化学镀（物料效率、拖出、废气）",
        "document": "STM BREF Draft 1 Ch.4.3.1",
        "source_file": "knowledge/bat/bat_electroplating_chemical_plating/bat-electroplating-chemical-plating.md",
    },
    # —— Stage 3 scoring rubric (PRD §8.5 — marking rules, not computed grades) ——
    {
        "id": "rubric_stage3_threshold_scoring",
        "layer": "rubric",
        "name_en": "Stage 3 · Threshold scoring (rule-based marking)",
        "name_zh": "阶段三 · 阈值评分（规则打分）",
        "document": "PRD §8.5 / backend/app/services/threshold_scoring.py",
        "stage": "3",
        "note_en": "Pure comparison logic — no LLM. Outputs CISA grade, CBAM risk tier, de minimis flag.",
        "note_zh": "纯比较逻辑 — 无 LLM。输出 CISA 等级、CBAM 风险档、微量豁免可能标志。",
    },
    {
        "id": "rubric_cisa_grade_e_to_a",
        "layer": "rubric",
        "name_en": "Marking · CISA low-carbon steel grade E→A (provisional)",
        "name_zh": "评分标尺 · CISA 低碳排放钢等级 E→A（暂行）",
        "document": "T/CISA 452 draft · app/data/cisa_tiers.py",
        "stage": "3",
        "marks": ["E", "D", "C", "B", "A"],
        "is_provisional": True,
        "note_en": "Boundaries provisional until finalized T/CISA text is verified — do not invent grades in prose.",
        "note_zh": "边界值在终稿核验前为暂行 — 顾问文案不得编造等级。",
    },
    {
        "id": "rubric_cbam_risk_tier",
        "layer": "rubric",
        "name_en": "Marking · CBAM risk tier (exempt / exposed / high_exposure)",
        "name_zh": "评分标尺 · CBAM 风险档（豁免 / 暴露 / 高暴露）",
        "document": "PRD §8.5 · threshold_scoring._cbam_risk_tier",
        "stage": "3",
        "marks": ["exempt", "exposed", "high_exposure"],
        "rule_en": "exempt if taxable intensity ≤ 0; high_exposure if gross tariff ≥ €150/t; else exposed",
        "rule_zh": "应税强度≤0 → exempt；毛关税≥€150/t → high_exposure；否则 exposed",
    },
    {
        "id": "rubric_de_minimis_50t",
        "layer": "rubric",
        "name_en": "Marking · De minimis possible (≤50 t/y export)",
        "name_zh": "评分标尺 · 微量豁免可能（年出口≤50吨）",
        "document": "PRD §6.3 / §8.5 · DE_MINIMIS_THRESHOLD_TONNES = 50",
        "stage": "3",
        "threshold_tonnes": 50.0,
        "rule_en": "SME tonnage ≤50t ⇒ de_minimis_possible=True (importer-side, never guaranteed exempt)",
        "rule_zh": "SME 吨位≤50t ⇒ de_minimis_possible=True（进口商侧判定，不可保证豁免）",
    },
    {
        "id": "rubric_eu_benchmark_gap",
        "layer": "rubric",
        "name_en": "Marking · EU benchmark gap (taxable emissions)",
        "name_zh": "评分标尺 · 欧盟基准差距（应税排放）",
        "document": "PRD §8.5 · calculation_engine + score_calculation",
        "stage": "3",
        "rule_en": "Intensity at/below EU route benchmark ⇒ taxable = 0 (valid exempt-tier outcome)",
        "rule_zh": "强度≤欧盟路线基准 ⇒ 应税=0（合法豁免档结果，非错误）",
    },
    # —— CBAM boundary / monitoring rule ——
    {
        "id": "rule_3162",
        "layer": "boundary",
        "name_en": "Reg (EU) 2025/2547 Annex I §3.16.2 — steel fabrication monitoring",
        "name_zh": "欧盟法规 2025/2547 附件一 §3.16.2 · 钢铁深加工监测边界",
        "document": "Regulation (EU) 2025/2547 Annex I Section 3.16.2",
        "included_processes": ["re-heating", "pickling", "annealing", "galvanising", "coating"],
        "excluded_direct_processes": ["cutting", "welding", "finishing", "mobile_machinery"],
    },
    {
        "id": "bound_included_direct",
        "layer": "boundary",
        "name_en": "CBAM boundary · Included direct",
        "name_zh": "CBAM 边界 · 直接排放计入",
        "tag": "Included_Direct",
    },
    {
        "id": "bound_excluded_direct",
        "layer": "boundary",
        "name_en": "CBAM boundary · Excluded direct",
        "name_zh": "CBAM 边界 · 直接排放排除",
        "tag": "Excluded_Direct",
    },
    {
        "id": "bound_relevant_precursor",
        "layer": "boundary",
        "name_en": "CBAM boundary · Relevant precursor",
        "name_zh": "CBAM 边界 · 相关前体",
        "tag": "Relevant_Precursor",
    },
    # —— Emission source tags ——
    {
        "id": "emis_scope1_combustion",
        "layer": "emission",
        "name_en": "Scope 1 · Combustion",
        "name_zh": "范围一 · 燃烧",
        "tag": "Scope1_Combustion",
    },
    {
        "id": "emis_scope1_process",
        "layer": "emission",
        "name_en": "Scope 1 · Process reduction",
        "name_zh": "范围一 · 工艺还原",
        "tag": "Scope1_Process_Reduction",
    },
    {
        "id": "emis_scope2_grid",
        "layer": "emission",
        "name_en": "Scope 2 · Grid electricity",
        "name_zh": "范围二 · 电网电力",
        "tag": "Scope2_GridElectricity",
        "cbam_steel_note_en": "Annex II iron/steel: electricity is not CBAM-priced; may inform financing scores only.",
        "cbam_steel_note_zh": "附件二钢铁：电力不计入 CBAM 计价；仅可进入绿色融资评分。",
    },
    # —— Upstream Baowu processes ——
    {
        "id": "proc_sintering",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Sintering",
        "name_zh": "烧结",
        "emission_tier": "RED",
    },
    {
        "id": "proc_coking",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Coking",
        "name_zh": "炼焦",
        "emission_tier": "RED",
    },
    {
        "id": "proc_blast_furnace",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Blast Furnace (BF)",
        "name_zh": "高炉（BF）",
        "emission_tier": "RED",
    },
    {
        "id": "proc_bof",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Basic Oxygen Furnace (BOF)",
        "name_zh": "转炉（BOF）",
        "emission_tier": "RED",
    },
    {
        "id": "proc_eaf",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Electric Arc Furnace (EAF)",
        "name_zh": "电弧炉（EAF）",
        "emission_tier": "ORANGE",
    },
    {
        "id": "proc_continuous_casting",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Continuous Casting",
        "name_zh": "连铸",
        "emission_tier": "ORANGE",
    },
    {
        "id": "proc_hot_rolling",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Hot Rolling Mill",
        "name_zh": "热轧",
        "emission_tier": "ORANGE",
    },
    # —— Downstream SME fabrication ——
    {
        "id": "proc_cnc_cutting",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "CNC Cutting (laser/plasma/oxy-fuel)",
        "name_zh": "数控切割（激光/等离子/火焰）",
        "equipment": "Laser/Plasma Cutter",
    },
    {
        "id": "proc_punching",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Punching & Drilling",
        "name_zh": "冲孔与钻孔",
    },
    {
        "id": "proc_co2_welding",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "CO₂ Shielded Welding",
        "name_zh": "二氧化碳保护焊",
        "equipment": "MIG/SAW Welder",
    },
    {
        "id": "proc_bending_milling",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Bending & Milling",
        "name_zh": "折弯与铣削",
    },
    {
        "id": "proc_assembly",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Assembly",
        "name_zh": "装配",
    },
    {
        "id": "proc_hot_dip_galvanizing",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Hot-Dip Galvanizing",
        "name_zh": "热浸镀锌",
        "equipment": "Zinc Bath Furnace",
    },
    # —— Materials ——
    {
        "id": "mat_iron_ore",
        "layer": "material",
        "name_en": "Iron Ore",
        "name_zh": "铁矿石",
    },
    {
        "id": "mat_coke",
        "layer": "material",
        "name_en": "Metallurgical Coke",
        "name_zh": "冶金焦",
    },
    {
        "id": "mat_pig_iron",
        "layer": "material",
        "name_en": "Pig Iron / Hot Metal",
        "name_zh": "生铁 / 铁水",
    },
    {
        "id": "mat_steel_scrap",
        "layer": "material",
        "name_en": "Steel Scrap",
        "name_zh": "废钢",
    },
    {
        "id": "mat_crude_steel_slab",
        "layer": "material",
        "name_en": "Crude Steel / Slab",
        "name_zh": "粗钢 / 板坯",
    },
    {
        "id": "mat_hot_rolled_plate",
        "layer": "material",
        "name_en": "Hot-Rolled Plate / Coil",
        "name_zh": "热轧板 / 卷",
    },
    {
        "id": "mat_fastener_bolt",
        "layer": "material",
        "name_en": "Finished Fastener (bolt/screw)",
        "name_zh": "成品紧固件（螺栓/螺钉）",
    },
    {
        "id": "mat_steel_structure",
        "layer": "material",
        "name_en": "Fabricated Steel Structure / Beams (EN 1090)",
        "name_zh": "建筑钢结构构件 / 梁柱（EN 1090）",
    },
    {
        "id": "mat_zinc_coating",
        "layer": "material",
        "name_en": "Zinc Coating",
        "name_zh": "锌镀层",
    },
    # —— Customs (PRD §6.1 only) ——
    {
        "id": "cn_7207",
        "layer": "customs",
        "cn_code": "7207",
        "name_en": "CN 7207 · Semi-finished billets",
        "name_zh": "CN 7207 · 半成品钢坯",
    },
    {
        "id": "cn_7208_10_00",
        "layer": "customs",
        "cn_code": "7208 10 00",
        "name_en": "CN 7208 10 00 · Hot-rolled coil",
        "name_zh": "CN 7208 10 00 · 热轧卷板",
    },
    {
        "id": "cn_7213",
        "layer": "customs",
        "cn_code": "7213",
        "name_en": "CN 7213 · Hot-rolled bars",
        "name_zh": "CN 7213 · 热轧盘条",
    },
    {
        "id": "cn_7214",
        "layer": "customs",
        "cn_code": "7214",
        "name_en": "CN 7214 · Hot-rolled wire rod",
        "name_zh": "CN 7214 · 热轧线材",
    },
    {
        "id": "cn_7301",
        "layer": "customs",
        "cn_code": "7301",
        "name_en": "CN 7301 · Sheet piling / angles",
        "name_zh": "CN 7301 · 板桩 / 角钢",
    },
    {
        "id": "cn_7302",
        "layer": "customs",
        "cn_code": "7302",
        "name_en": "CN 7302 · Railway track material",
        "name_zh": "CN 7302 · 铁路轨道材料",
    },
    {
        "id": "cn_7308",
        "layer": "customs",
        "cn_code": "7308",
        "name_en": "CN 7308 · Fabricated steel structures (EN 1090)",
        "name_zh": "CN 7308 · 钢铁结构体及部件（EN 1090）",
    },
    {
        "id": "cn_7318_15_42",
        "layer": "customs",
        "cn_code": "7318 15 42",
        "name_en": "CN 7318 15 42 · Bolts",
        "name_zh": "CN 7318 15 42 · 螺栓",
    },
    {
        "id": "cn_7318_15_88",
        "layer": "customs",
        "cn_code": "7318 15 88",
        "name_en": "CN 7318 15 88 · Screws",
        "name_zh": "CN 7318 15 88 · 螺钉",
    },
    {
        "id": "cn_7326",
        "layer": "customs",
        "cn_code": "7326",
        "name_en": "CN 7326 · Other steel articles",
        "name_zh": "CN 7326 · 其他钢铁制品",
    },
]

# ---------------------------------------------------------------------------
# Edges — undirected storage in NetworkX MultiDiGraph; rel on edge data
# ---------------------------------------------------------------------------

EDGES: list[dict[str, Any]] = [
    # Upstream material flow
    {"source": "proc_sintering", "target": "mat_iron_ore", "rel": "CONSUMES"},
    {"source": "proc_coking", "target": "mat_coke", "rel": "PRODUCES"},
    {"source": "proc_blast_furnace", "target": "mat_iron_ore", "rel": "CONSUMES"},
    {"source": "proc_blast_furnace", "target": "mat_coke", "rel": "CONSUMES"},
    {"source": "proc_blast_furnace", "target": "mat_pig_iron", "rel": "PRODUCES"},
    {"source": "proc_blast_furnace", "target": "emis_scope1_process", "rel": "EMITS"},
    {"source": "proc_bof", "target": "mat_pig_iron", "rel": "CONSUMES"},
    {"source": "proc_bof", "target": "mat_crude_steel_slab", "rel": "PRODUCES"},
    {"source": "proc_bof", "target": "emis_scope1_process", "rel": "EMITS"},
    {"source": "proc_eaf", "target": "mat_steel_scrap", "rel": "CONSUMES"},
    {"source": "proc_eaf", "target": "mat_crude_steel_slab", "rel": "PRODUCES"},
    {"source": "proc_eaf", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_continuous_casting", "target": "mat_crude_steel_slab", "rel": "CONSUMES"},
    {"source": "proc_continuous_casting", "target": "emis_scope1_combustion", "rel": "EMITS"},
    {"source": "proc_continuous_casting", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_hot_rolling", "target": "mat_crude_steel_slab", "rel": "CONSUMES"},
    {"source": "proc_hot_rolling", "target": "mat_hot_rolled_plate", "rel": "PRODUCES"},
    {"source": "proc_hot_rolling", "target": "emis_scope1_combustion", "rel": "EMITS"},
    {"source": "proc_hot_rolling", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_blast_furnace", "target": "proc_bof", "rel": "FEEDS"},
    {"source": "proc_bof", "target": "proc_continuous_casting", "rel": "FEEDS"},
    {"source": "proc_continuous_casting", "target": "proc_hot_rolling", "rel": "FEEDS"},
    # Customs linkage
    {"source": "mat_crude_steel_slab", "target": "cn_7207", "rel": "HAS_CN_CODE"},
    {"source": "mat_hot_rolled_plate", "target": "cn_7208_10_00", "rel": "HAS_CN_CODE"},
    {"source": "mat_hot_rolled_plate", "target": "bound_relevant_precursor", "rel": "CLASSIFIED_AS"},
    {
        "source": "mat_hot_rolled_plate",
        "target": "mat_fastener_bolt",
        "rel": "PRECURSOR_OF",
        "yield_factor_m": 1.176,
        "scrap_pct": 15.0,
        "note_en": "15% fabrication scrap → m_plate = 1/0.85 ≈ 1.176 t plate / t fastener",
        "note_zh": "加工废料 15% → m_板 = 1/0.85 ≈ 1.176 吨板材 / 吨紧固件",
    },
    {"source": "mat_fastener_bolt", "target": "cn_7318_15_42", "rel": "HAS_CN_CODE"},
    {"source": "mat_fastener_bolt", "target": "cn_7318_15_88", "rel": "HAS_CN_CODE"},
    {
        "source": "mat_hot_rolled_plate",
        "target": "mat_steel_structure",
        "rel": "PRECURSOR_OF",
        "yield_factor_m": 1.176,
        "scrap_pct": 15.0,
        "note_en": "15% fabrication scrap → m_plate = 1/0.85 ≈ 1.176 t plate / t structure",
        "note_zh": "加工废料 15% → m_板 = 1/0.85 ≈ 1.176 吨板材 / 吨结构件",
    },
    {"source": "mat_steel_structure", "target": "cn_7308", "rel": "HAS_CN_CODE"},
    # Downstream process emissions & governance
    {
        "source": "proc_cnc_cutting",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
        "cite": "Reg (EU) 2025/2547 Annex I §3.16.2 — cutting excluded from direct process emissions",
    },
    {"source": "proc_cnc_cutting", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_cnc_cutting", "target": "bound_excluded_direct", "rel": "CLASSIFIED_AS"},
    {
        "source": "proc_co2_welding",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
        "cite": "Reg (EU) 2025/2547 Annex I §3.16.2 — welding excluded from direct process emissions",
    },
    {"source": "proc_co2_welding", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_co2_welding", "target": "bound_excluded_direct", "rel": "CLASSIFIED_AS"},
    {
        "source": "proc_punching",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
    },
    {"source": "proc_punching", "target": "emis_scope2_grid", "rel": "EMITS"},
    {
        "source": "proc_bending_milling",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
    },
    {"source": "proc_bending_milling", "target": "emis_scope2_grid", "rel": "EMITS"},
    {
        "source": "proc_assembly",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
        "cite": "Mobile forklift diesel excluded (Annex II §B.1.c style mobile machinery)",
    },
    {"source": "proc_assembly", "target": "emis_scope2_grid", "rel": "EMITS"},
    {
        "source": "proc_hot_dip_galvanizing",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "INCLUDED",
        "indirect_status": "INCLUDED",
        "cite": "§3.16.2 mandates monitoring for galvanising / coating",
    },
    {"source": "proc_hot_dip_galvanizing", "target": "emis_scope1_combustion", "rel": "EMITS"},
    {"source": "proc_hot_dip_galvanizing", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_hot_dip_galvanizing", "target": "bound_included_direct", "rel": "CLASSIFIED_AS"},
    {"source": "proc_hot_dip_galvanizing", "target": "mat_zinc_coating", "rel": "CONSUMES"},
    {"source": "proc_cnc_cutting", "target": "mat_hot_rolled_plate", "rel": "CONSUMES"},
    {"source": "proc_punching", "target": "mat_hot_rolled_plate", "rel": "CONSUMES"},
    {"source": "proc_hot_dip_galvanizing", "target": "mat_fastener_bolt", "rel": "PRODUCES"},
    {"source": "proc_hot_dip_galvanizing", "target": "mat_steel_structure", "rel": "PRODUCES"},
    # BAT guidance (STM BREF KB — citation only)
    {"source": "bat_stm_bref_root", "target": "bat_pretreatment_pickling", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_zinc_chromium_plating", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_continuous_coil_coating", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_steel_enamelling", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_cross_cutting_ems_energy", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_cross_cutting_decarb_water", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_cross_cutting_crvi_substitution", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_cross_cutting_air_noise", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_cross_cutting_wastewater", "rel": "INCLUDES_BAT"},
    {"source": "bat_stm_bref_root", "target": "bat_electroplating_specific", "rel": "INCLUDES_BAT"},
    {
        "source": "proc_hot_dip_galvanizing",
        "target": "bat_zinc_chromium_plating",
        "rel": "GUIDED_BY_BAT",
        "cite": "STM BREF Ch.2.2.1 — zinc/chromium plating & conversion for fasteners",
    },
    {
        "source": "proc_hot_dip_galvanizing",
        "target": "bat_pretreatment_pickling",
        "rel": "GUIDED_BY_BAT",
        "cite": "STM BREF Ch.2.1.4 — pickling/descaling before coating",
    },
    {
        "source": "proc_hot_dip_galvanizing",
        "target": "bat_electroplating_specific",
        "rel": "GUIDED_BY_BAT",
        "cite": "STM BREF Ch.4.3.1 — electroplating BAT (drag-out, material efficiency)",
    },
    {
        "source": "mat_zinc_coating",
        "target": "bat_zinc_chromium_plating",
        "rel": "GUIDED_BY_BAT",
    },
    {
        "source": "mat_zinc_coating",
        "target": "bat_cross_cutting_crvi_substitution",
        "rel": "GUIDED_BY_BAT",
        "cite": "Cr(VI) substitution for passivation / conversion coatings",
    },
    {
        "source": "mat_hot_rolled_plate",
        "target": "bat_continuous_coil_coating",
        "rel": "GUIDED_BY_BAT",
        "cite": "Upstream coil may be coated on Baowu/Ansteel continuous lines",
    },
    {
        "source": "mat_fastener_bolt",
        "target": "bat_zinc_chromium_plating",
        "rel": "GUIDED_BY_BAT",
    },
    {
        "source": "mat_fastener_bolt",
        "target": "bat_cross_cutting_crvi_substitution",
        "rel": "GUIDED_BY_BAT",
    },
    {
        "source": "rule_3162",
        "target": "bat_zinc_chromium_plating",
        "rel": "ALIGNED_WITH_BAT",
        "cite": "§3.16.2 included galvanising/coating ↔ STM plating BAT",
    },
    # Stage 3 scoring rubric (marking rules — numbers still from threshold_scoring)
    {
        "source": "rubric_stage3_threshold_scoring",
        "target": "rubric_cisa_grade_e_to_a",
        "rel": "INCLUDES_RUBRIC",
    },
    {
        "source": "rubric_stage3_threshold_scoring",
        "target": "rubric_cbam_risk_tier",
        "rel": "INCLUDES_RUBRIC",
    },
    {
        "source": "rubric_stage3_threshold_scoring",
        "target": "rubric_de_minimis_50t",
        "rel": "INCLUDES_RUBRIC",
    },
    {
        "source": "rubric_stage3_threshold_scoring",
        "target": "rubric_eu_benchmark_gap",
        "rel": "INCLUDES_RUBRIC",
    },
    {
        "source": "mat_fastener_bolt",
        "target": "rubric_stage3_threshold_scoring",
        "rel": "SCORED_BY",
        "cite": "PRD §8.5 — intensity vs CISA + EU benchmark after calculation engine",
    },
    {
        "source": "mat_steel_structure",
        "target": "rubric_stage3_threshold_scoring",
        "rel": "SCORED_BY",
    },
    {
        "source": "cn_7318_15_42",
        "target": "rubric_stage3_threshold_scoring",
        "rel": "SCORED_BY",
    },
    {
        "source": "cn_7318_15_88",
        "target": "rubric_stage3_threshold_scoring",
        "rel": "SCORED_BY",
    },
    {
        "source": "cn_7208_10_00",
        "target": "rubric_stage3_threshold_scoring",
        "rel": "SCORED_BY",
    },
    {
        "source": "cn_7308",
        "target": "rubric_stage3_threshold_scoring",
        "rel": "SCORED_BY",
    },
    {
        "source": "mat_hot_rolled_plate",
        "target": "rubric_eu_benchmark_gap",
        "rel": "SCORED_BY",
        "cite": "Precursor intensity feeds Stage-3 EU benchmark gap",
    },
    {
        "source": "bound_included_direct",
        "target": "rubric_cbam_risk_tier",
        "rel": "INFORMS_RUBRIC",
    },
]
