"""Seed ontology for GreenGru industrial metallurgical & regulatory Graph RAG.

Four layers: Physical process lineage → Material/precursor flows →
CBAM regulatory boundaries → China’s 十五五 policy directives.

CN customs nodes cover PRD §6.1 steel products, supporting both downstream
fasteners (CN 7318) and fabricated steel structures / EN 1090 beams (CN 7308).

Annex II iron/steel note: CBAM certificates price *direct* emissions.
Electricity (Scope 2) may appear as MONITORING_ONLY_NOT_CBAM_PRICED for
advisory clarity and financing scores — never as a CBAM tariff input.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Nodes — id is stable; name_en / name_zh for bilingual UI
# ---------------------------------------------------------------------------

NODES: list[dict[str, Any]] = [
    # —— Policy (十五五) ——
    {
        "id": "policy_15_5_ch21_s2",
        "layer": "policy",
        "name_en": "15th FYP Ch.21 §2 — Carbon footprint mutual recognition",
        "name_zh": "十五五 · 第21章第2节 · 产品碳足迹国际互认",
        "plan": "15th Five-Year Plan",
        "section": "Chapter 21 Section 2",
    },
    {
        "id": "policy_15_5_ch18_s2",
        "layer": "policy",
        "name_en": "15th FYP Ch.18 §2 — Large–SME supply-chain synergy",
        "name_zh": "十五五 · 第18章第2节 · 大中小企业供应链协同",
        "plan": "15th Five-Year Plan",
        "section": "Chapter 18 Section 2",
    },
    {
        "id": "policy_15_5_ch47_s1",
        "layer": "policy",
        "name_en": "15th FYP Ch.47 §1 — Dual control (volume & intensity)",
        "name_zh": "十五五 · 第47章第1节 · 碳排放双控",
        "plan": "15th Five-Year Plan",
        "section": "Chapter 47 Section 1",
    },
    # —— CBAM boundary / monitoring rule ——
    {
        "id": "rule_3162",
        "layer": "boundary",
        "name_en": "Reg (EU) 2025/2547 Annex I §3.16.2 — steel fabrication monitoring",
        "name_zh": "欧盟法规 2025/2547 附件一 §3.16.2 · 钢铁深加工监测边界",
        "document": "Regulation (EU) 2025/2547 Annex I Section 3.16.2",
        "included_processes": ["re-heating", "pickling", "annealing", "galvanising", "coating"],
        "excluded_direct_processes": ["cutting", "welding", "finishing", "mobile_machinery"],
    },
    {
        "id": "bound_included_direct",
        "layer": "boundary",
        "name_en": "CBAM boundary · Included direct",
        "name_zh": "CBAM 边界 · 直接排放计入",
        "tag": "Included_Direct",
    },
    {
        "id": "bound_excluded_direct",
        "layer": "boundary",
        "name_en": "CBAM boundary · Excluded direct",
        "name_zh": "CBAM 边界 · 直接排放排除",
        "tag": "Excluded_Direct",
    },
    {
        "id": "bound_relevant_precursor",
        "layer": "boundary",
        "name_en": "CBAM boundary · Relevant precursor",
        "name_zh": "CBAM 边界 · 相关前体",
        "tag": "Relevant_Precursor",
    },
    # —— Emission source tags ——
    {
        "id": "emis_scope1_combustion",
        "layer": "emission",
        "name_en": "Scope 1 · Combustion",
        "name_zh": "范围一 · 燃烧",
        "tag": "Scope1_Combustion",
    },
    {
        "id": "emis_scope1_process",
        "layer": "emission",
        "name_en": "Scope 1 · Process reduction",
        "name_zh": "范围一 · 工艺还原",
        "tag": "Scope1_Process_Reduction",
    },
    {
        "id": "emis_scope2_grid",
        "layer": "emission",
        "name_en": "Scope 2 · Grid electricity",
        "name_zh": "范围二 · 电网电力",
        "tag": "Scope2_GridElectricity",
        "cbam_steel_note_en": "Annex II iron/steel: electricity is not CBAM-priced; may inform financing scores only.",
        "cbam_steel_note_zh": "附件二钢铁：电力不计入 CBAM 计价；仅可进入绿色融资评分。",
    },
    # —— Upstream Baowu processes ——
    {
        "id": "proc_sintering",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Sintering",
        "name_zh": "烧结",
        "emission_tier": "RED",
    },
    {
        "id": "proc_coking",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Coking",
        "name_zh": "炼焦",
        "emission_tier": "RED",
    },
    {
        "id": "proc_blast_furnace",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Blast Furnace (BF)",
        "name_zh": "高炉（BF）",
        "emission_tier": "RED",
    },
    {
        "id": "proc_bof",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Basic Oxygen Furnace (BOF)",
        "name_zh": "转炉（BOF）",
        "emission_tier": "RED",
    },
    {
        "id": "proc_eaf",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Electric Arc Furnace (EAF)",
        "name_zh": "电弧炉（EAF）",
        "emission_tier": "ORANGE",
    },
    {
        "id": "proc_continuous_casting",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Continuous Casting",
        "name_zh": "连铸",
        "emission_tier": "ORANGE",
    },
    {
        "id": "proc_hot_rolling",
        "layer": "process",
        "stage": "upstream",
        "operator": "Baowu",
        "name_en": "Hot Rolling Mill",
        "name_zh": "热轧",
        "emission_tier": "ORANGE",
    },
    # —— Downstream SME fabrication ——
    {
        "id": "proc_cnc_cutting",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "CNC Cutting (laser/plasma/oxy-fuel)",
        "name_zh": "数控切割（激光/等离子/火焰）",
        "equipment": "Laser/Plasma Cutter",
    },
    {
        "id": "proc_punching",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Punching & Drilling",
        "name_zh": "冲孔与钻孔",
    },
    {
        "id": "proc_co2_welding",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "CO₂ Shielded Welding",
        "name_zh": "二氧化碳保护焊",
        "equipment": "MIG/SAW Welder",
    },
    {
        "id": "proc_bending_milling",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Bending & Milling",
        "name_zh": "折弯与铣削",
    },
    {
        "id": "proc_assembly",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Assembly",
        "name_zh": "装配",
    },
    {
        "id": "proc_hot_dip_galvanizing",
        "layer": "process",
        "stage": "downstream",
        "operator": "SME",
        "name_en": "Hot-Dip Galvanizing",
        "name_zh": "热浸镀锌",
        "equipment": "Zinc Bath Furnace",
    },
    # —— Materials ——
    {
        "id": "mat_iron_ore",
        "layer": "material",
        "name_en": "Iron Ore",
        "name_zh": "铁矿石",
    },
    {
        "id": "mat_coke",
        "layer": "material",
        "name_en": "Metallurgical Coke",
        "name_zh": "冶金焦",
    },
    {
        "id": "mat_pig_iron",
        "layer": "material",
        "name_en": "Pig Iron / Hot Metal",
        "name_zh": "生铁 / 铁水",
    },
    {
        "id": "mat_steel_scrap",
        "layer": "material",
        "name_en": "Steel Scrap",
        "name_zh": "废钢",
    },
    {
        "id": "mat_crude_steel_slab",
        "layer": "material",
        "name_en": "Crude Steel / Slab",
        "name_zh": "粗钢 / 板坯",
    },
    {
        "id": "mat_hot_rolled_plate",
        "layer": "material",
        "name_en": "Hot-Rolled Plate / Coil",
        "name_zh": "热轧板 / 卷",
    },
    {
        "id": "mat_fastener_bolt",
        "layer": "material",
        "name_en": "Finished Fastener (bolt/screw)",
        "name_zh": "成品紧固件（螺栓/螺钉）",
    },
    {
        "id": "mat_steel_structure",
        "layer": "material",
        "name_en": "Fabricated Steel Structure / Beams (EN 1090)",
        "name_zh": "建筑钢结构构件 / 梁柱（EN 1090）",
    },
    {
        "id": "mat_zinc_coating",
        "layer": "material",
        "name_en": "Zinc Coating",
        "name_zh": "锌镀层",
    },
    # —— Customs (PRD §6.1 only) ——
    {
        "id": "cn_7207",
        "layer": "customs",
        "cn_code": "7207",
        "name_en": "CN 7207 · Semi-finished billets",
        "name_zh": "CN 7207 · 半成品钢坯",
    },
    {
        "id": "cn_7208_10_00",
        "layer": "customs",
        "cn_code": "7208 10 00",
        "name_en": "CN 7208 10 00 · Hot-rolled coil",
        "name_zh": "CN 7208 10 00 · 热轧卷板",
    },
    {
        "id": "cn_7213",
        "layer": "customs",
        "cn_code": "7213",
        "name_en": "CN 7213 · Hot-rolled bars",
        "name_zh": "CN 7213 · 热轧盘条",
    },
    {
        "id": "cn_7214",
        "layer": "customs",
        "cn_code": "7214",
        "name_en": "CN 7214 · Hot-rolled wire rod",
        "name_zh": "CN 7214 · 热轧线材",
    },
    {
        "id": "cn_7301",
        "layer": "customs",
        "cn_code": "7301",
        "name_en": "CN 7301 · Sheet piling / angles",
        "name_zh": "CN 7301 · 板桩 / 角钢",
    },
    {
        "id": "cn_7302",
        "layer": "customs",
        "cn_code": "7302",
        "name_en": "CN 7302 · Railway track material",
        "name_zh": "CN 7302 · 铁路轨道材料",
    },
    {
        "id": "cn_7308",
        "layer": "customs",
        "cn_code": "7308",
        "name_en": "CN 7308 · Fabricated steel structures (EN 1090)",
        "name_zh": "CN 7308 · 钢铁结构体及部件（EN 1090）",
    },
    {
        "id": "cn_7318_15_42",
        "layer": "customs",
        "cn_code": "7318 15 42",
        "name_en": "CN 7318 15 42 · Bolts",
        "name_zh": "CN 7318 15 42 · 螺栓",
    },
    {
        "id": "cn_7318_15_88",
        "layer": "customs",
        "cn_code": "7318 15 88",
        "name_en": "CN 7318 15 88 · Screws",
        "name_zh": "CN 7318 15 88 · 螺钉",
    },
    {
        "id": "cn_7326",
        "layer": "customs",
        "cn_code": "7326",
        "name_en": "CN 7326 · Other steel articles",
        "name_zh": "CN 7326 · 其他钢铁制品",
    },
]

# ---------------------------------------------------------------------------
# Edges — undirected storage in NetworkX MultiDiGraph; rel on edge data
# ---------------------------------------------------------------------------

EDGES: list[dict[str, Any]] = [
    # Upstream material flow
    {"source": "proc_sintering", "target": "mat_iron_ore", "rel": "CONSUMES"},
    {"source": "proc_coking", "target": "mat_coke", "rel": "PRODUCES"},
    {"source": "proc_blast_furnace", "target": "mat_iron_ore", "rel": "CONSUMES"},
    {"source": "proc_blast_furnace", "target": "mat_coke", "rel": "CONSUMES"},
    {"source": "proc_blast_furnace", "target": "mat_pig_iron", "rel": "PRODUCES"},
    {"source": "proc_blast_furnace", "target": "emis_scope1_process", "rel": "EMITS"},
    {"source": "proc_bof", "target": "mat_pig_iron", "rel": "CONSUMES"},
    {"source": "proc_bof", "target": "mat_crude_steel_slab", "rel": "PRODUCES"},
    {"source": "proc_bof", "target": "emis_scope1_process", "rel": "EMITS"},
    {"source": "proc_eaf", "target": "mat_steel_scrap", "rel": "CONSUMES"},
    {"source": "proc_eaf", "target": "mat_crude_steel_slab", "rel": "PRODUCES"},
    {"source": "proc_eaf", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_continuous_casting", "target": "mat_crude_steel_slab", "rel": "CONSUMES"},
    {"source": "proc_continuous_casting", "target": "emis_scope1_combustion", "rel": "EMITS"},
    {"source": "proc_continuous_casting", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_hot_rolling", "target": "mat_crude_steel_slab", "rel": "CONSUMES"},
    {"source": "proc_hot_rolling", "target": "mat_hot_rolled_plate", "rel": "PRODUCES"},
    {"source": "proc_hot_rolling", "target": "emis_scope1_combustion", "rel": "EMITS"},
    {"source": "proc_hot_rolling", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_blast_furnace", "target": "proc_bof", "rel": "FEEDS"},
    {"source": "proc_bof", "target": "proc_continuous_casting", "rel": "FEEDS"},
    {"source": "proc_continuous_casting", "target": "proc_hot_rolling", "rel": "FEEDS"},
    # Customs linkage
    {"source": "mat_crude_steel_slab", "target": "cn_7207", "rel": "HAS_CN_CODE"},
    {"source": "mat_hot_rolled_plate", "target": "cn_7208_10_00", "rel": "HAS_CN_CODE"},
    {"source": "mat_hot_rolled_plate", "target": "bound_relevant_precursor", "rel": "CLASSIFIED_AS"},
    {
        "source": "mat_hot_rolled_plate",
        "target": "mat_fastener_bolt",
        "rel": "PRECURSOR_OF",
        "yield_factor_m": 1.176,
        "scrap_pct": 15.0,
        "note_en": "15% fabrication scrap → m_plate = 1/0.85 ≈ 1.176 t plate / t fastener",
        "note_zh": "加工废料 15% → m_板 = 1/0.85 ≈ 1.176 吨板材 / 吨紧固件",
    },
    {"source": "mat_fastener_bolt", "target": "cn_7318_15_42", "rel": "HAS_CN_CODE"},
    {"source": "mat_fastener_bolt", "target": "cn_7318_15_88", "rel": "HAS_CN_CODE"},
    {
        "source": "mat_hot_rolled_plate",
        "target": "mat_steel_structure",
        "rel": "PRECURSOR_OF",
        "yield_factor_m": 1.176,
        "scrap_pct": 15.0,
        "note_en": "15% fabrication scrap → m_plate = 1/0.85 ≈ 1.176 t plate / t structure",
        "note_zh": "加工废料 15% → m_板 = 1/0.85 ≈ 1.176 吨板材 / 吨结构件",
    },
    {"source": "mat_steel_structure", "target": "cn_7308", "rel": "HAS_CN_CODE"},
    # Downstream process emissions & governance
    {
        "source": "proc_cnc_cutting",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
        "cite": "Reg (EU) 2025/2547 Annex I §3.16.2 — cutting excluded from direct process emissions",
    },
    {"source": "proc_cnc_cutting", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_cnc_cutting", "target": "bound_excluded_direct", "rel": "CLASSIFIED_AS"},
    {
        "source": "proc_co2_welding",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
        "cite": "Reg (EU) 2025/2547 Annex I §3.16.2 — welding excluded from direct process emissions",
    },
    {"source": "proc_co2_welding", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_co2_welding", "target": "bound_excluded_direct", "rel": "CLASSIFIED_AS"},
    {
        "source": "proc_punching",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
    },
    {"source": "proc_punching", "target": "emis_scope2_grid", "rel": "EMITS"},
    {
        "source": "proc_bending_milling",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
    },
    {"source": "proc_bending_milling", "target": "emis_scope2_grid", "rel": "EMITS"},
    {
        "source": "proc_assembly",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "EXCLUDED",
        "indirect_status": "MONITORING_ONLY_NOT_CBAM_PRICED",
        "cite": "Mobile forklift diesel excluded (Annex II §B.1.c style mobile machinery)",
    },
    {"source": "proc_assembly", "target": "emis_scope2_grid", "rel": "EMITS"},
    {
        "source": "proc_hot_dip_galvanizing",
        "target": "rule_3162",
        "rel": "GOVERNED_BY",
        "direct_status": "INCLUDED",
        "indirect_status": "INCLUDED",
        "cite": "§3.16.2 mandates monitoring for galvanising / coating",
    },
    {"source": "proc_hot_dip_galvanizing", "target": "emis_scope1_combustion", "rel": "EMITS"},
    {"source": "proc_hot_dip_galvanizing", "target": "emis_scope2_grid", "rel": "EMITS"},
    {"source": "proc_hot_dip_galvanizing", "target": "bound_included_direct", "rel": "CLASSIFIED_AS"},
    {"source": "proc_hot_dip_galvanizing", "target": "mat_zinc_coating", "rel": "CONSUMES"},
    {"source": "proc_cnc_cutting", "target": "mat_hot_rolled_plate", "rel": "CONSUMES"},
    {"source": "proc_punching", "target": "mat_hot_rolled_plate", "rel": "CONSUMES"},
    {"source": "proc_hot_dip_galvanizing", "target": "mat_fastener_bolt", "rel": "PRODUCES"},
    {"source": "proc_hot_dip_galvanizing", "target": "mat_steel_structure", "rel": "PRODUCES"},
    # Policy alignment
    {"source": "cn_7318_15_88", "target": "policy_15_5_ch21_s2", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "cn_7318_15_42", "target": "policy_15_5_ch21_s2", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "cn_7308", "target": "policy_15_5_ch21_s2", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "cn_7208_10_00", "target": "policy_15_5_ch18_s2", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "proc_blast_furnace", "target": "policy_15_5_ch47_s1", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "proc_bof", "target": "policy_15_5_ch18_s2", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "mat_fastener_bolt", "target": "policy_15_5_ch21_s2", "rel": "ALIGNED_WITH_POLICY"},
    {"source": "mat_steel_structure", "target": "policy_15_5_ch21_s2", "rel": "ALIGNED_WITH_POLICY"},
]
