/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpstreamRouteImport } from './routes/upstream'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as GrantRouteImport } from './routes/grant'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CnArticlesFullApiDocumentationRouteImport } from './routes/cn/articles/full-api-documentation'

const UpstreamRoute = UpstreamRouteImport.update({
  id: '/upstream',
  path: '/upstream',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantRoute = GrantRouteImport.update({
  id: '/grant',
  path: '/grant',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CnArticlesFullApiDocumentationRoute =
  CnArticlesFullApiDocumentationRouteImport.update({
    id: '/cn/articles/full-api-documentation',
    path: '/cn/articles/full-api-documentation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entry': typeof EntryRoute
  '/grant': typeof GrantRoute
  '/loan': typeof LoanRoute
  '/new': typeof NewRoute
  '/passport': typeof PassportRoute
  '/signin': typeof SigninRoute
  '/upstream': typeof UpstreamRoute
  '/cn/articles/full-api-documentation': typeof CnArticlesFullApiDocumentationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entry': typeof EntryRoute
  '/grant': typeof GrantRoute
  '/loan': typeof LoanRoute
  '/new': typeof NewRoute
  '/passport': typeof PassportRoute
  '/signin': typeof SigninRoute
  '/upstream': typeof UpstreamRoute
  '/cn/articles/full-api-documentation': typeof CnArticlesFullApiDocumentationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entry': typeof EntryRoute
  '/grant': typeof GrantRoute
  '/loan': typeof LoanRoute
  '/new': typeof NewRoute
  '/passport': typeof PassportRoute
  '/signin': typeof SigninRoute
  '/upstream': typeof UpstreamRoute
  '/cn/articles/full-api-documentation': typeof CnArticlesFullApiDocumentationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entry'
    | '/grant'
    | '/loan'
    | '/new'
    | '/passport'
    | '/signin'
    | '/upstream'
    | '/cn/articles/full-api-documentation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entry'
    | '/grant'
    | '/loan'
    | '/new'
    | '/passport'
    | '/signin'
    | '/upstream'
    | '/cn/articles/full-api-documentation'
  id:
    | '__root__'
    | '/'
    | '/entry'
    | '/grant'
    | '/loan'
    | '/new'
    | '/passport'
    | '/signin'
    | '/upstream'
    | '/cn/articles/full-api-documentation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntryRoute: typeof EntryRoute
  GrantRoute: typeof GrantRoute
  LoanRoute: typeof LoanRoute
  NewRoute: typeof NewRoute
  PassportRoute: typeof PassportRoute
  SigninRoute: typeof SigninRoute
  UpstreamRoute: typeof UpstreamRoute
  CnArticlesFullApiDocumentationRoute: typeof CnArticlesFullApiDocumentationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upstream': {
      id: '/upstream'
      path: '/upstream'
      fullPath: '/upstream'
      preLoaderRoute: typeof UpstreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant': {
      id: '/grant'
      path: '/grant'
      fullPath: '/grant'
      preLoaderRoute: typeof GrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cn/articles/full-api-documentation': {
      id: '/cn/articles/full-api-documentation'
      path: '/cn/articles/full-api-documentation'
      fullPath: '/cn/articles/full-api-documentation'
      preLoaderRoute: typeof CnArticlesFullApiDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntryRoute: EntryRoute,
  GrantRoute: GrantRoute,
  LoanRoute: LoanRoute,
  NewRoute: NewRoute,
  PassportRoute: PassportRoute,
  SigninRoute: SigninRoute,
  UpstreamRoute: UpstreamRoute,
  CnArticlesFullApiDocumentationRoute: CnArticlesFullApiDocumentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
